sonar.projectKey=eeshanoor_selenium-web-automation
sonar.projectName=Selenium Web Automation
sonar.projectVersion=1.0
sonar.sources=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.qualitygate.wait=true